### ISSUE TITLE
로고 이미지 변경의 건

### ISSUE THREAD

**Issue by ksahn29** [Beomi/irkshop#1]
좌측 메뉴단의 사이트 로고 외곽선이 깔끔하지 못한데, 열어 보니 그림파일 자체의 문제로 판단하여 png 파일로 새로 작업하여 업로드합니다. 검토 부탁드리고, 수정 필요한 경우 DM 부탁드립니다.
![logo_3_new](https://cloud.githubusercontent.com/assets/6817065/19517864/b3322c9a-963e-11e6-8063-c8227523a446.png)

**Comment by Beomi** [comment]
[#c95ad94](https://github.com/Beomi/irkshop/commit/c95ad94) 커밋에서 변경하였습니다.
