### ISSUE TITLE
Social media button

### ISSUE THREAD

**Issue by ksahn29** [Beomi/irkshop#4]
facebook과 google plus 버튼입니다. 스캐너에 쓰이는 coda 폰트로 만들었고, H × W = 50 px × 50 px입니다. 
![facebook](https://cloud.githubusercontent.com/assets/6817065/19528961/06e7368a-9669-11e6-9279-477deb08a6d6.png)
![googleplus](https://cloud.githubusercontent.com/assets/6817065/19528960/06df2972-9669-11e6-979c-3e2f9edd3441.png)

**Comment by Beomi** [comment]
혹시 DPI 2배 가능할까요?

**Comment by ksahn29** [comment]
HiDPI를 깜빡했네요. 뽀뽀샵이 먹통이 되는 바람에 다시 작업했습니다. 위 이미지랑 살짝 달라요.
![facebook-2x](https://cloud.githubusercontent.com/assets/6817065/19562225/79f2aa4e-9716-11e6-8319-6a5e04309979.png)
![googleplus-2x](https://cloud.githubusercontent.com/assets/6817065/19562278/abae1744-9716-11e6-89f0-90240b2b6143.png)

**Comment by Beomi** [comment]
[#0497940](https://github.com/Beomi/irkshop/commit/0497940) 업로드했습니다.
